{{- if .Values.shippingservice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    {{- include "microservices-demo.service.labels" (dict "serviceName" "shippingservice" "component" "backend" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.shippingservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "microservices-demo.service.selectorLabels" (dict "serviceName" "shippingservice") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservices-demo.service.labels" (dict "serviceName" "shippingservice" "component" "backend" "context" .) | nindent 8 }}
    spec:
      serviceAccountName: shippingservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: {{ include "microservices-demo.image" (dict "context" . "service" .Values.shippingservice) }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: {{ .Values.shippingservice.port }}
          protocol: TCP
        env:
        - name: PORT
          value: {{ .Values.shippingservice.port | quote }}
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          {{- toYaml .Values.shippingservice.resources | nindent 10 }}
        readinessProbe:
          grpc:
            port: {{ .Values.shippingservice.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: {{ .Values.shippingservice.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    {{- include "microservices-demo.service.labels" (dict "serviceName" "shippingservice" "component" "backend" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "microservices-demo.service.selectorLabels" (dict "serviceName" "shippingservice") | nindent 4 }}
  ports:
  - name: grpc
    port: {{ .Values.shippingservice.port }}
    targetPort: {{ .Values.shippingservice.port }}
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  labels:
    {{- include "microservices-demo.service.labels" (dict "serviceName" "shippingservice" "component" "backend" "context" .) | nindent 4 }}
{{- end }}
