name: Container Image CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'microservices-demo/src/**'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by GitHub Actions
  ECR_REGISTRY_URI: ${{ secrets.ECR_REGISTRY_URI }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  discover_services:
    name: Discover Microservices
    uses: ./.github/workflows/reusable_discover-app-services.yaml

  create_sem_ver: 
    needs: discover_services
    if: ${{ needs.discover_services.outputs.services != '[]' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJson(needs.discover_services.outputs.services) }}

    steps:
      - uses: actions/checkout@v4

      - name: Create version tag
        id: create_version_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_NAME: ${{ matrix.service }}
        run: |
          CURRENT_VERSION_TAG=$(git ls-remote --tags origin "refs/tags/${SERVICE_NAME}-v*" | awk -F'/' '{print $3}' | sort -V | tail -n1)
          if [ -z "$CURRENT_VERSION_TAG" ]; then
            NEW_VERSION_TAG="${SERVICE_NAME}-v1.0.0"
          else
            VERSION_NUMBER=${CURRENT_VERSION_TAG#${SERVICE_NAME}-v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUMBER"
            PATCH=$((PATCH + 1))
            NEW_VERSION_TAG="${SERVICE_NAME}-v${MAJOR}.${MINOR}.${PATCH}"
          fi
          echo "New version tag for service ${SERVICE_NAME}: $NEW_VERSION_TAG"
          echo "version_tag=$NEW_VERSION_TAG" >> "$GITHUB_OUTPUT"

  build_and_scan:
    needs: discover_services
    if: ${{ needs.discover_services.outputs.services != '[]' }}

    runs-on: ubuntu-latest
    
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      pull-requests: write # for creating pull requests with scan results

    strategy:
      matrix:
        service: ${{ fromJson(needs.discover_services.outputs.services) }}

    env:
      IMAGE_TAG: ${{ matrix.service }}:ci-${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./microservices-demo/src/${{ matrix.service }}
          file: ./microservices-demo/src/${{ matrix.service }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ECR_REGISTRY_URI }}/${{ matrix.service }}:${{ github.ref_name }}
            ${{ env.ECR_REGISTRY_URI }}/${{ matrix.service }}:latest